
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: kind-slave
      env: pro
    # Connecting with the other cluster to remote write metrics
    remoteWrite: 
      - url: https://receiver-write.example.com:8443/api/v1/receive

# enable --web.enable-remote-write-receiver flag on prometheus-server
    enableRemoteWriteReceiver: true

## Component scraping kube state metrics
##
kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

grafana:
  enabled: false

alertmanager:
  enabled: false